import {
  deployCommands,
  hostedDatabaseSetupCommands,
  hostedOperatorNotes,
  identitySetupSteps,
  billingSyncSetupCommands,
  netlifyProjectSetupReceiptCommands,
  netlifySiteLinkCommands,
  hostedEnvironmentSetupCommands,
  launchPacketArtifacts,
  launchPacketCommands,
  previewSmokeCommands,
  secretCommands,
  verificationCommands,
} from '../src/lib/hosted-remediation';

const lines = [
  'ClaimBot hosted setup checklist',
  '',
  '0. Required values to gather before launch:',
  '   - Placeholder template: .env.hosted.example',
  '   - Hosted database URL, such as libsql://YOUR_DATABASE.turso.io',
  '   - Hosted database auth token if using libSQL/Turso',
  '   - Non-secret hosted database packet from npm run hosted:db:packet',
  '   - Non-secret source readiness packet from npm run source:packet',
  '   - Public contact URL for the scraper user agent',
  '   - Monitored support email address',
  '   - Non-secret operator setup packet from npm run operator:packet',
  '   - Generated launch smoke secrets from npm run launch:secrets',
  '   - Processor-hosted Plus and Pro checkout links',
  '   - Generated billing sync secret or Stripe webhook endpoint secret for signed processor events',
  '   - Non-secret billing activation packet from npm run billing:packet',
  '   - Legal/compliance review packet and acknowledgment after review is complete',
  '   - Non-secret PWA readiness packet from npm run pwa:packet',
  '   - Non-secret deployability packet from npm run deploy:packet',
  '',
  '1. Link the Netlify site:',
  ...netlifySiteLinkCommands.map((command) => `   ${command}`),
  '   npm run operator:packet',
  '   npm run netlify:doctor',
  '   - Do not reuse an unrelated Netlify project. If this app has no ClaimBot site yet, create a dedicated one first.',
  '',
  '2. Enable Netlify Identity for hosted login:',
  ...identitySetupSteps.map((step) => `   - ${step}`),
  '   # After confirming those dashboard settings, write the non-secret setup receipt:',
  ...netlifyProjectSetupReceiptCommands.map((command) => `   ${command}`),
  '',
  '3. Generate launch smoke secrets and keep them out of committed files:',
  ...secretCommands.map((command) => `   ${command}`),
  '   # The generated .env.launch.local file is ignored by git and does not print secret values.',
  '   # After Netlify CLI login, push the generated session and billing sync secrets without printing them:',
  '   npm run launch:push-secrets',
  '',
  '4. Prepare, migrate, import, and push the hosted database without printing secrets:',
  ...hostedDatabaseSetupCommands.map((command) => `   ${command}`),
  '   # Review data/hosted-database-packet.md for schema, source export, and hosted import evidence.',
  '   # Review data/source-readiness-packet.md for source coverage, digest, claim-form coverage, and matcher input readiness.',
  '   # The generated .env.hosted.local file is ignored by git and should hold only local operator secrets.',
  '',
  '5. Optional one-file hosted env push. Replace placeholders before running:',
  ...hostedEnvironmentSetupCommands.map((command) => `   ${command}`),
  '   # Review data/operator-setup-packet.md before inviting clients or sending login links.',
  '   # The doctor checks the one-file handoff without writing to Netlify; the push applies launch-critical database, support, billing, legal, feature, and secret env values without printing them.',
  '',
  '6. Set production and deploy-preview environment variables manually. Replace placeholders before running:',
  ...deployCommands.map((command) => `   ${command}`),
  '',
  '7. Billing checkout links:',
  '   netlify env:set CLAIMBOT_BILLING_PLUS_MONTHLY_URL "https://YOUR_PROCESSOR_CHECKOUT_LINK" --context production deploy-preview',
  '   netlify env:set CLAIMBOT_BILLING_PRO_MONTHLY_URL "https://YOUR_PROCESSOR_CHECKOUT_LINK" --context production deploy-preview',
  '   # Generate a separate billing sync secret, or set the Stripe endpoint secret:',
  ...billingSyncSetupCommands.map((command) => `   ${command}`),
  '   # Review data/billing-activation-packet.md before treating paid CTAs as launch-ready.',
  '',
  '8. Optional integrations:',
  '   netlify env:set DISCORD_WEBHOOK_URL "YOUR_WEBHOOK_URL" --secret --context production',
  '   netlify env:set HIBP_API_KEY "YOUR_HIBP_KEY" --secret --context production',
  '',
  '9. Legal/compliance review gate:',
  '   npm run legal:packet',
  '   npm run validate:legal',
  '   # Review data/legal-review-packet.md plus the deployed Terms, Privacy Policy, trust copy, proof handling, authorization gates, pricing, billing sync, and filing posture first.',
  '   netlify env:set CLAIMBOT_LEGAL_REVIEW_ACK "reviewed" --context production deploy-preview',
  '',
  '10. Generate and review the complete non-secret launch packet stack:',
  ...launchPacketCommands.map((command) => `   ${command}`),
  '   # Review data/external-activation-workbook.md for the current external owners, proof files, and starter commands.',
  '   # Review data/client-preview-checklist.md for the current product-requirement completion audit before inviting clients.',
  '   # Packet stack artifacts:',
  ...launchPacketArtifacts.map((artifact) => `   - ${artifact.path}: ${artifact.proof}`),
  '   # The Launch and Packet Center pages count a packet as ready only when its JSON companion readiness gate is clear.',
  '',
  '11. Validate and deploy:',
  ...verificationCommands.map((command) => `   ${command}`),
  '',
  '12. Prove the local hosted access gate:',
  '   npm run smoke:hosted:local',
  '   # This command is included in the validation list above; rerun it when you need a fresh local smoke receipt.',
  '   # It starts a fresh local web-smoke target, then runs auth and feature smokes sequentially unless SMOKE_BASE_URL points at a deployed preview.',
  '   # It also verifies /api/audit/support-packet includes databaseSchema, sourceCatalog, source quality, and text encoding launch evidence.',
  '   # It verifies /api/audit/support-packet includes netlifyPreview evidence and marks operator-local smoke inputs as not server-observable.',
  '   # With SMOKE_BASE_URL set, it probes /.netlify/identity/user so deployed previews prove Netlify Identity is enabled.',
  '   # With SMOKE_BASE_URL set, it also fails if the hosted support packet does not show an imported source catalog with claim-form, source-quality, and clean text-encoding readiness.',
  '',
  '13. Smoke the deployed preview before production:',
  '   netlify deploy',
  '   npm run preview:packet',
  '   # PowerShell:',
  ...previewSmokeCommands.map((command) => `   ${command}`),
  '   npm run netlify:doctor:strict',
  '   npm run preview:gate',
  '   npm run preview:packet',
  '   npm run production:check-receipt',
  '   netlify deploy --prod',
  '',
  'Safety defaults:',
  ...hostedOperatorNotes.map((note) => `- ${note}`),
  '- Preview promotion should require npm run preview:gate, which sequences validate:secrets, validate:netlify:strict, validate:routes, validate:ui, validate:legal, validate:pwa, validate:hosted, db:migrate, validate:schema, validate:source, enrich:source, source:export, validate:source:strict, source:import:dry, build:hosted, smoke:web, smoke:auth, and smoke:features.',
  '- Hosted database bootstrap should use npm run hosted:db:prepare, npm run hosted:db:doctor, npm run with:hosted-env -- npm run db:migrate, npm run with:hosted-env -- npm run source:import:dry, npm run with:hosted-env -- npm run source:import, and npm run hosted:db:push.',
  '- Netlify launch-critical env commands target production and deploy-preview contexts so the deployed preview proves the same hosted gates before production promotion.',
  '- Client preview promotion keeps CLAIMBOT_FEATURE_SETTLEMENT_SEARCH=true because the core product promise depends on settlement discovery and claim-search surfaces.',
  '- Use validate:source:strict, source:export, and source:import when the hosted database needs the enriched local source catalog before preview promotion; source:import:dry must pass against the hosted database before production promotion.',
  '- The support packet must show launchEvidence.databaseSchema.ok=true and launchEvidence.sourceCatalog readiness before client launch review.',
  '- The support packet must show launchEvidence.netlifyPreview evidence; HTTPS SMOKE_BASE_URL and smoke secrets are operator-local and are proved by validate:netlify:strict plus preview:gate.',
  '- Run npm run matcher:receipt so the support packet can show launchEvidence.matcherRunReceipt from MATCHER_RUN_COMPLETED before relying on client-facing matcher results.',
  '- A successful deployed-preview gate writes data/preview-promotion-receipt.json; production promotion should run production:check-receipt before netlify deploy --prod.',
  '- Run npm run preview:packet before and after preview:gate; review data/preview-promotion-packet.md for target, receipt, and command evidence.',
  '- npm run launch:handoff writes data/launch-handoff-report.json and data/launch-handoff-report.md without secrets for operator handoff.',
  '- npm run activation:workbook writes data/external-activation-workbook.json and data/external-activation-workbook.md without secrets for the current external setup runbook.',
  '- npm run client:checklist writes data/client-preview-checklist.json and data/client-preview-checklist.md without secrets for the current product-requirement completion audit.',
  '- npm run hosted:env:prepare, npm run hosted:env:doctor, and npm run hosted:env:push provide the one-file Netlify env path; the older hosted:db:* and launch:push-secrets commands remain available for narrower database/secret-only updates.',
  '- Public-discovery client previews should review launchEvidence.sourceCatalog totals, formCoveragePercent, deadlineCoveragePercent, knownAdministratorPercent, categorizedPercent, textEncodingReady, mojibakeCount, and readiness items.',
  '- The installed/offline shell is only a safety page; claim data, legal decisions, and filing state require reconnecting to the hosted app.',
  '- Local dev-server smokes should run through npm run smoke:hosted:local; it starts a fresh web target and avoids parallel port/startup contention between smoke:web, smoke:auth, and smoke:features.',
];

console.log(lines.join('\n'));
